/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface DogFunHome {
        "breed": string;
        "match": MatchResults;
        "subbreed": string;
    }
    interface ImageGallery {
        "breed": string;
        "subbreed": string;
    }
    interface ImgbtnCombo {
        "breed": string;
        "subbreed": string;
    }
    interface PopupImage {
        "match": MatchResults;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDogFunHomeElement extends Components.DogFunHome, HTMLStencilElement {
    }
    var HTMLDogFunHomeElement: {
        prototype: HTMLDogFunHomeElement;
        new (): HTMLDogFunHomeElement;
    };
    interface HTMLImageGalleryElement extends Components.ImageGallery, HTMLStencilElement {
    }
    var HTMLImageGalleryElement: {
        prototype: HTMLImageGalleryElement;
        new (): HTMLImageGalleryElement;
    };
    interface HTMLImgbtnComboElement extends Components.ImgbtnCombo, HTMLStencilElement {
    }
    var HTMLImgbtnComboElement: {
        prototype: HTMLImgbtnComboElement;
        new (): HTMLImgbtnComboElement;
    };
    interface HTMLPopupImageElement extends Components.PopupImage, HTMLStencilElement {
    }
    var HTMLPopupImageElement: {
        prototype: HTMLPopupImageElement;
        new (): HTMLPopupImageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "dog-fun-home": HTMLDogFunHomeElement;
        "image-gallery": HTMLImageGalleryElement;
        "imgbtn-combo": HTMLImgbtnComboElement;
        "popup-image": HTMLPopupImageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DogFunHome {
        "breed"?: string;
        "match"?: MatchResults;
        "subbreed"?: string;
    }
    interface ImageGallery {
        "breed"?: string;
        "subbreed"?: string;
    }
    interface ImgbtnCombo {
        "breed"?: string;
        "subbreed"?: string;
    }
    interface PopupImage {
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "dog-fun-home": DogFunHome;
        "image-gallery": ImageGallery;
        "imgbtn-combo": ImgbtnCombo;
        "popup-image": PopupImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dog-fun-home": LocalJSX.DogFunHome & JSXBase.HTMLAttributes<HTMLDogFunHomeElement>;
            "image-gallery": LocalJSX.ImageGallery & JSXBase.HTMLAttributes<HTMLImageGalleryElement>;
            "imgbtn-combo": LocalJSX.ImgbtnCombo & JSXBase.HTMLAttributes<HTMLImgbtnComboElement>;
            "popup-image": LocalJSX.PopupImage & JSXBase.HTMLAttributes<HTMLPopupImageElement>;
        }
    }
}
